---
- name: Configuración para instalar iptables
  hosts: localhost
  become: true

  tasks:
    - name: Copiar script
      copy: 'src=/root/Scripts/Puesta_a_punto/instalar_iptables.sh dest=/root/Scripts/Puesta_a_punto/'
    - name: Ejecutar script
      command: "/root/Scripts/Puesta_a_punto/instalar_iptables.sh"
