---
- name: Programar tarea cron para el script de mysql
  hosts: localhost
  become: true

  tasks:
    - name: Agregar tarea cron para el script de mysql
      ansible.builtin.cron:
        name: "Ejecutar script de respaldo de MySQL"
        minute: "0"
        hour: "2"
        job: "/root/Scripts/Backup/respaldo_mysql.sh"

    - name: Agregar tarea cron para el script de respaldo
      ansible.builtin.cron:
        name: "Ejecutar script de respaldo de Scripts"
        minute: "0"
        hour: "2"
        job: "/root/Scripts/Backup/respaldo_scripts.sh"

    - name: Crear el crontab para ejecutar el script a las 2 AM
      cron:
        name: "Respaldar usuarios"
        minute: "0"
        hour: "2"
        job: "/root/Scripts/Backup/respaldo_usuarios.sh"
