---
- name: Programar tarea cron para el script de respaldo
  hosts: localhost
  become: true

  tasks:
    - name: Agregar tarea cron para el script de respaldo
      ansible.builtin.cron:
        name: "Ejecutar script de respaldo de Scripts"
        minute: "0"
        hour: "2"
        job: "/root/Scripts/Backup/respaldo_scripts.sh"
