---
- name: Instalar PHP en CentOS7
  hosts: localhost
  become: yes
  tasks:
    - name: Instalar repositorio EPEL
      yum:
        name: epel-release
        state: present

    - name: Instalar PHP y modulos
      yum:
        name:
          - php
          - php-common
          - php-cli
          - php-fpm
          - php-mysql
          - php-gd
          - php-xml
        state: present
    - name: Reiniciar servicio PHP-FPM
      service:
          name: php-fpm
          state: restarted
