---
- name: Configurar crontab para instalar mysql
  hosts: localhost
  become: true

  tasks:
    - name: Crear el crontab para ejecutar el script a las 2 AM
      cron:
        name: "Instalar mysql"
        minute: "0"
        hour: "2"
        job: "/root/Scripts/Puesta_a_punto/instalar_mysql.sh"
